image:
  tag: 8.13.4

replicas: 1
minimumMasterNodes: 1

security:
  enabled: false

sysctlImage:
  enabled: true

volumeClaimTemplate:
  resources:
    requests:
      storage: 10Gi

global:
  storageClass: ebs-sc

volumePermissions:
  enabled: true  # 권한 문제 해결

master:
  masterOnly: false     # 마스터가 모든 역할을 하도록 설정
  replicaCount: 1       # 마스터 노드 수: 1개
  nodeSelector:
    workload: streaming-infra
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 1
      memory: 2Gi
      
  podTemplate: # Pod 템플릿을 정의하는 섹션 (차트별로 다를 수 있음)
    spec:
      containers:
        - name: elasticsearch # 컨테이너 이름 (차트에서 사용하는 이름 확인 필요)
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms1g -Xmx1g" # 최소 1GB 힙 메모리 설정

data:
  replicaCount: 0       # 데이터 노드 사용 안 함
coordinating:
  replicaCount: 0       # coordinating 노드 사용 안 함
ingest:
  replicaCount: 0       # ingest 노드 사용 안 함

clusterHealthCheckParams: "wait_for_status=green&timeout=1s"
