apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
      - name: chat
        image: harbor.shoong.store/chat-backend/develop:13
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
      env:
          # === KAFKA ===
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka.kafka.svc.cluster.local:9092"
          - name: MONGO_DB_URI
            valueFrom:
              secretKeyRef:
                name: chat-backend-secret
                key: mongodb_host
