apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  labels:
    app: chat-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
      - name: chat
        image: harbor.shoong.store/chat-backend/develop:27
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          # === KAFKA ===
          - name: KAFKA_BOOTSTRAP_SERVERS
            value: "kafka.kafka.svc.cluster.local:9092"
          # === MONGODB ===
          - name: MONGO_DB_URI
            valueFrom:
              secretKeyRef:
                name: chat-backend-secret
                key: mongodb_host
          - name: MONGO_DB_PORT
            value: "27017"
          - name: MONGO_DB_NAME
            value: "chatDB"
