apiVersion: v1
kind: Service
metadata:
  name: chat-backend
  namespace: chat-backend
  labels:
    app: chat-backend
spec:
  selector:
    app: chat-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP