{
 "title": "AWS CloudFront",
 "description": "Visualize AWS CloudFront metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "distributionid",
    "label": "DistributionId",
    "query": "dimension_values(us-east-1, AWS/CloudFront, Requests, DistributionId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / TotalErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "4xxErrorRate / 5xxErrorRate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BytesDownloaded / BytesUploaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "<a target=\"_blank\" href=\"http://www.monitoringartist.com\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a> | \n<a target=\"_blank\" href=\"https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/viewing-cloudfront-metrics.html#monitoring-console.distributions\">AWS CloudWatch Cloudfront documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/dashboards/674\">Installed from Grafana.com dashboards</a>"
   }
  }
 ]
}