{
 "title": "EFG",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "liveId",
    "label": "liveId",
    "query": "{\"find\": \"terms\", \"field\": \"liveId.keyword\"}"
   },
   {
    "name": "itemId",
    "label": "itemId",
    "query": "{\"find\": \"terms\", \"field\": \"itemId.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "라이브 진행중 통계",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "상품을 조회한 수",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType: item_detail AND itemId: $itemId",
     "timeField": "@timestamp"
    },
    {
     "alias": "장바구니에 담은 수",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType: cart_added AND itemId: $itemId",
     "timeField": "@timestamp"
    },
    {
     "alias": "결제한 수",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType: order_finalized AND itemId: $itemId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "상품별 장바구니 담긴 횟수",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "logs" }
     ],
     "query": "eventType:\"cart_added\" AND itemId: $itemId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "상품 전체 조회수",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType:\"item_detail\" AND itemId: $itemId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "상품별 결제 횟수",
   "type": "stat",
   "description": "라이브 시간 내 상품별 결제 횟수\n필요한 것 : itemId, liveId, start time, end time",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType:\"purchase\" AND itemId: $itemId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "상품 조회 횟수",
   "type": "timeseries",
   "description": "라이브 시간 내 상품 조회 횟수",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType:\"item_detail\" AND itemId:$itemId",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "연령대별 구매 통계",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 14, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "ageGroup.keyword",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "eventType: \"order_finalized\" AND liveId: $liveId",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}