apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-backend
  namespace: backend
  labels:
    app: web-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-backend
  template:
    metadata:
      labels:
        app: web-backend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - web-backend
                topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: workload
                    operator: In
                    values:
                      - was
      containers:
      - name: web-backend
        image: harbor.shoong.store/shoong-backend/develop:72
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
        env:
          # === DB ===
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: db_host
          - name: DB_PORT
            value: "6033"
          - name: DB_NAME
            value: "shoong"
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: db_password

          # === JWT ===
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: jwt_secret

          # === REDIS ===
          - name: REDIS_HOST
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: redis_host
          - name: REDIS_PORT
            value: "6379"

          # === Kakao OAuth ===
          - name: REST_API_KEY
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: kakao_client_id

          # === AWS ===
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: aws_secret_key
          - name: AWS_REGION
            value: "ap-northeast-2"
          - name: S3_BUCKET_NAME
            valueFrom:
              secretKeyRef:
                name: web-backend-secret
                key: s3_bucket_name

        resources:
          requests:
            memory: "512Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
          - name: log-volume
            mountPath: /app/logs

      - name: fluent-bit
        image: fluent/fluent-bit:2.2
        resources:
          limits:
            memory: "200Mi"
            cpu: "100m"
          requests:
            memory: "100Mi"
            cpu: "50m"
        volumeMounts:
          - name: log-volume
            mountPath: /app/logs
          - name: fluent-bit-config
            mountPath: /fluent-bit/etc
            readOnly: true

      volumes:
        - name: log-volume
          emptyDir: {}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
