apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: chat-backend-secret
  namespace: backend
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: chat-backend-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: shoong/chat-backend
