apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chat-backend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SHOONG-SHOONG/k8s-manifests.git
    targetRevision: develop
    path: apps/chat-backend
  destination:
    server: https://kubernetes.default.svc
    namespace: chat-backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
